### ISSUE TITLE
Publish to Hackage/Stackage with basic Constraint support

### ISSUE THREAD

**Issue by ProofOfKeags** [brendanhay/semver#10]
I'd like to get the most recent changes I made to add constraint support into hackage/stackage. What needs to be done to get this to happen?

**Comment by ProofOfKeags** [comment]
Bump.

Also, If you don't have the bandwidth/interest to maintain this package, I'd be interested in taking it over. Our product makes extensive use of semver/ranges and I think we can allocate time to it.

**Comment by brendanhay** [comment]
Thanks, I've added you as a collaborater so feel free to go ham.

Version `0.4.0.1` has been released to [Hackage](https://hackage.haskell.org/package/semver), apologies for the delay.

There were some build failures on [Hackage CI](https://matrix.hackage.haskell.org/#/package/semver/0.4.0/ghc-8.2.2@1604135874) regarding `<>` implicit imports in the `.Constraints` module -with `0.4.0`, hence the patch level bump.

* `0.4.0` has a metadata revision so it'll only build on GHC >= 8.2.*
* `0.4.0.1` has a metadata revision so it'll only build on GHC >= 7.6.*
