### ISSUE TITLE
Comparison operators & range specification

### ISSUE THREAD

**Issue by dahlia** [brendanhay/semver#4]
Although Semantic Versioning itself does not deal with range specification, [some](http://python-semanticversion.readthedocs.org/en/latest/#requirement-specification) [implementations](https://github.com/npm/node-semver#ranges) provide range specification.  Such feature would be very useful.

**Comment by brendanhay** [comment]
I'll have a look into it, thanks for the links.

**Comment by ProofOfKeags** [comment]
I think I addressed this desire in #8
